### ISSUE TITLE
many duplicate log items in hippocampus

### ISSUE THREAD

**Issue by rcoreilly** [Astera-org/models#16]

**Comment by qemqemqem** [comment]
I'm actively working on fixing logging for hippocampus.

**Comment by qemqemqem** [comment]
This should be resolved now. We were accidentally adding all logging items twice. 

https://github.com/Astera-org/models/commit/aab16358e6ce6a1c5d114fd55788724f53451e96#diff-75d9b624e4c51600283413399052ba2f563ab44643e44f81ace4b23386fbf29eL37
