### ISSUE TITLE
parts unit test: one-to-many mappings

### ISSUE THREAD

**Issue by rcoreilly** [Astera-org/models#3]
Create a model that learns one-to-many mappings: simplest case is one random input pattern and multiple random output patterns.

This is about being able to encode a distribution rather than a mean value. Theory suggests that spiking is very useful here. 

https://arxiv.org/abs/2111.09780 Paper from postdoc Kevin McKee in the CCN lab showing how synaptic failure produces a sampling process from distribution.  Spiking noise is also important. The Axon model does a good job of representing more than just mean: variance and multi-modal distributions too.  Relates to attention and constraint satisfaction models too.

*Notes RA25 model, create multiple distribution

**Comment by wumpusman** [comment]
Modify RA25*

**Comment by qemqemqem** [comment]
Added in one2many

https://github.com/Astera-org/models/blob/master/mechs/one2many/one2many.go
